apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-sqs-example-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: keda-sqs-example
    envSourceContainerName: keda-sqs-example-jvm
  pollingInterval: 30
  cooldownPeriod:  30  # Default: 300 seconds
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: <<QUEUE_URL>>
        queueLength: "1"  # Default: "5"
        awsRegion: "us-east-1"
        identityOwner: pod
      authenticationRef:
        name: localstack-auth
        kind: TriggerAuthentication