apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: keda-sqs-example
  name: keda-sqs-example
spec:
  ports:
  - name: 9091-9091
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: keda-sqs-example
  type: NodePort
status:
  loadBalancer: {}
